Repository boostcampth/boostcamp3_H, pull requests merged in 2019-01, with the labels that each got.

#36 Feature #035 util network state check
  .idea/runConfigurations.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/team_h/boostcamp/myapplication/utils/NetworkStatueUtil.java
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: Feature, 원종성

#37 Feature #032 hashpaser
  app/src/main/java/team_h/boostcamp/myapplication/utils/HashTagPaser.java
  app/src/test/java/team_h/boostcamp/myapplication/utils/HashTagPaserTest.java
Labels: 매우간단

#38 Feature #033 util SharedPreference
  app/src/main/java/team_h/boostcamp/myapplication/util/SharedPreference.java
  app/src/test/java/team_h/boostcamp/myapplication/util/SharedPreferenceTest.java
Labels: Feature

#40 Feature #039 common architecture
  .idea/runConfigurations.xml
  app/build.gradle
  app/src/androidTest/java/team_h/boostcamp/myapplication/utils/NetworkStatueUtilTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/team_h/boostcamp/myapplication/MainActivity.java
  app/src/main/java/team_h/boostcamp/myapplication/view/BaseActivity.java
  app/src/main/java/team_h/boostcamp/myapplication/view/BasePresenter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/BaseView.java
  app/src/main/java/team_h/boostcamp/myapplication/view/adapter/AdapterContract.java
  app/src/main/java/team_h/boostcamp/myapplication/view/adapter/BaseRecyclerViewAdapter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/adapter/OnItemClickListener.java
  app/src/main/java/team_h/boostcamp/myapplication/view/main/MainActivity.java
  app/src/main/java/team_h/boostcamp/myapplication/view/main/MainContractor.java
  app/src/main/java/team_h/boostcamp/myapplication/view/main/MainPresenter.java
  app/src/main/res/layout/activity_main.xml
  build.gradle
Labels: Feature, 원종성

#42 Fix_#041_버그수정
  .gitignore
  app/src/androidTest/java/team_h/boostcamp/myapplication/utils/NetworkStatueUtilTest.java
  app/src/main/java/team_h/boostcamp/myapplication/utils/HashTagParser.java
  app/src/main/java/team_h/boostcamp/myapplication/utils/SharedPreference.java
  app/src/main/java/team_h/boostcamp/myapplication/view/adapter/BaseRecyclerViewAdapter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/main/MainActivity.java
  app/src/test/java/team_h/boostcamp/myapplication/utils/HashTagPaserTest.java
Labels: bug, 원종성

#46 Fix_#045_BaseFragment 추가
  app/src/main/java/team_h/boostcamp/myapplication/view/BaseFragment.java
Labels: Fix, 원종성

#48 Feature #023 setting graph
  app/build.gradle
  app/src/androidTest/java/team_h/boostcamp/myapplication/ExampleInstrumentedTest.java
  app/src/androidTest/java/team_h/boostcamp/myapplication/utils/NetworkStateUtilTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/team_h/boostcamp/myapplication/utils/NetworkStateUtil.java
  app/src/main/java/team_h/boostcamp/myapplication/view/BaseActivity.java
  app/src/main/java/team_h/boostcamp/myapplication/view/BaseFragment.java
  app/src/main/java/team_h/boostcamp/myapplication/view/BaseView.java
  app/src/main/java/team_h/boostcamp/myapplication/view/adapter/BaseRecyclerViewAdapter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/graph/GraphAxisValueFormatter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/graph/GraphContractor.java
  app/src/main/java/team_h/boostcamp/myapplication/view/graph/GraphFragment.java
  app/src/main/java/team_h/boostcamp/myapplication/view/graph/GraphPresenter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/graph/GraphYAxisValueFormatter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/main/MainActivity.java
  app/src/main/java/team_h/boostcamp/myapplication/view/main/MainPresenter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/main/MainTabAdapter.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
  build.gradle
  gradle.properties
Labels: Feature, 이승우

#53 Fix #051 update base file
  .gitignore
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/team_h/boostcamp/myapplication/view/BaseActivity.java
  app/src/main/java/team_h/boostcamp/myapplication/view/BaseFragment.java
  app/src/main/java/team_h/boostcamp/myapplication/view/BaseView.java
  app/src/main/java/team_h/boostcamp/myapplication/view/adapter/BaseRecyclerViewAdapter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/graph/GraphFragment.java
  app/src/main/java/team_h/boostcamp/myapplication/view/main/MainActivity.java
  app/src/main/java/team_h/boostcamp/myapplication/view/main/MainContractor.java
  app/src/main/java/team_h/boostcamp/myapplication/view/main/MainPresenter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/main/MainTabAdapter.java
  boostCampShare.zip
Labels: Fix, 원종성

#54 Feature #050 resource util 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/team_h/boostcamp/myapplication/utils/ResourceSendUtil.java
  app/src/main/java/team_h/boostcamp/myapplication/view/main/MainActivity.java
  boostCampShare.zip
Labels: Feature, 매우간단, 원종성

#56 #017_feat_memoriesfragment
  .idea/misc.xml
  app/src/main/java/team_h/boostcamp/myapplication/model/Memory.java
  app/src/main/java/team_h/boostcamp/myapplication/view/main/MainActivity.java
  app/src/main/java/team_h/boostcamp/myapplication/view/memories/MemoriesCardAdapter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/memories/MemoriesContractor.java
  app/src/main/java/team_h/boostcamp/myapplication/view/memories/MemoriesDiaryAdapter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/memories/MemoriesFragment.java
  app/src/main/java/team_h/boostcamp/myapplication/view/memories/MemoriesPresenter.java
  app/src/main/res/drawable/ic_memories_close.xml
  app/src/main/res/drawable/ic_memories_play.xml
  app/src/main/res/layout/fragment_memories.xml
  app/src/main/res/layout/item_diary.xml
  app/src/main/res/layout/item_memory_card.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Feature, 이화중

#58 #000_fix_충돌 해결
  .idea/gradle.xml
  .idea/runConfigurations.xml
  app/src/main/java/team_h/boostcamp/myapplication/view/main/MainActivity.java
Labels: Fix, 이승우

#57 Feature #003 record layout
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/team_h/boostcamp/myapplication/view/customview/HashTagEditText.java
  app/src/main/java/team_h/boostcamp/myapplication/view/diaryList/DiaryListFragment.java
  app/src/main/res/drawable/bg_hash_tag_edittext.xml
  app/src/main/res/drawable/bg_mic_record_btn.xml
  app/src/main/res/drawable/ic_cancel_black_24dp.xml
  app/src/main/res/drawable/ic_mic_black_not_record_32dp.xml
  app/src/main/res/drawable/ic_play_circle_filled_black_24dp.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_diary_list.xml
  app/src/main/res/layout/item_record_diary.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Feature, 원종성

#59 Feature #049 fix graph y axix emoji
  .idea/gradle.xml
  .idea/runConfigurations.xml
  app/src/main/java/team_h/boostcamp/myapplication/utils/ResourceSendUtil.java
  app/src/main/java/team_h/boostcamp/myapplication/view/graph/GraphFragment.java
  app/src/main/java/team_h/boostcamp/myapplication/view/graph/GraphPresenter.java
  app/src/main/res/values/strings.xml
Labels: Fix, 이승우

#60 Feature #004 record diary
  .idea/gradle.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/team_h/boostcamp/myapplication/utils/KeyPadUtil.java
  app/src/main/java/team_h/boostcamp/myapplication/utils/ResourceSendUtil.java
  app/src/main/java/team_h/boostcamp/myapplication/view/BaseFragment.java
  app/src/main/java/team_h/boostcamp/myapplication/view/diaryList/DiaryContract.java
  app/src/main/java/team_h/boostcamp/myapplication/view/diaryList/DiaryListFragment.java
  app/src/main/java/team_h/boostcamp/myapplication/view/diaryList/DiaryPresenter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/diaryList/HashTagListAdapter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/graph/GraphPresenter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/main/MainActivity.java
  app/src/main/java/team_h/boostcamp/myapplication/view/memories/MemoriesFragment.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_diary_list.xml
  app/src/main/res/layout/item_hash_tag.xml
  app/src/main/res/values/strings.xml
Labels: Feature, 원종성

#62 #024_feat_해시 태그 xml에 추가
  app/src/main/java/team_h/boostcamp/myapplication/view/graph/GraphPresenter.java
  app/src/main/res/layout/fragment_graph.xml
Labels: Feature, 매우간단, 이승우

#65 Feature #063 show hash tag text
  app/src/main/java/team_h/boostcamp/myapplication/view/graph/GraphContractor.java
  app/src/main/java/team_h/boostcamp/myapplication/view/graph/GraphFragment.java
  app/src/main/java/team_h/boostcamp/myapplication/view/graph/GraphPresenter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/graph/HashTagCustomLayout.java
  app/src/main/res/layout/fragment_graph.xml
  app/src/main/res/layout/layout_graph_hash_tag.xml
Labels: Feature, 이승우

#66 Feature #064 audio analyze
  app/build.gradle
  app/src/androidTest/java/team_h/boostcamp/myapplication/ExampleInstrumentedTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/team_h/boostcamp/myapplication/api_service/APIClient.java
  app/src/main/java/team_h/boostcamp/myapplication/api_service/emotion/EmotionAnalysisAPI.java
  app/src/main/java/team_h/boostcamp/myapplication/api_service/emotion/EmotionAnalysisResponse.java
  app/src/main/java/team_h/boostcamp/myapplication/api_service/emotion/EmotionAnalyzeRequest.java
  app/src/main/java/team_h/boostcamp/myapplication/api_service/emotion/mapper/AnalyzedEmotionMapper.java
  app/src/main/java/team_h/boostcamp/myapplication/model/Diary.java
  app/src/main/java/team_h/boostcamp/myapplication/utils/NetworkStateUtil.java
  app/src/main/java/team_h/boostcamp/myapplication/utils/ResourceSendUtil.java
  app/src/main/java/team_h/boostcamp/myapplication/view/diaryList/DiaryContract.java
  app/src/main/java/team_h/boostcamp/myapplication/view/diaryList/DiaryListFragment.java
  app/src/main/java/team_h/boostcamp/myapplication/view/diaryList/DiaryPresenter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/diaryList/HashTagListAdapter.java
  app/src/main/res/anim/btn_scale_up_anim.xml
  app/src/main/res/layout/fragment_diary_list.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/team_h/boostcamp/myapplication/ExampleUnitTest.java
  
Labels: Feature, 원종성

#69 #068_feat_room
  app/build.gradle
  app/src/main/java/team_h/boostcamp/myapplication/model/Diary.java
  app/src/main/java/team_h/boostcamp/myapplication/model/Memory.java
  app/src/main/java/team_h/boostcamp/myapplication/model/Recommendation.java
  app/src/main/java/team_h/boostcamp/myapplication/model/source/local/AppDao.java
  app/src/main/java/team_h/boostcamp/myapplication/model/source/local/AppDatabase.java
  app/src/main/java/team_h/boostcamp/myapplication/view/diaryList/DiaryListFragment.java
  app/src/main/java/team_h/boostcamp/myapplication/view/diaryList/DiaryPresenter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/graph/HashTagCustomLayout.java
  app/src/main/res/layout/fragment_diary_list.xml
  app/src/main/res/layout/item_record_diary.xml
  app/src/main/res/values/strings.xml
Labels: Feature, 원종성

#71 Feature #070 save record
  app/build.gradle
  app/src/main/java/team_h/boostcamp/myapplication/api_service/APIClient.java
  app/src/main/java/team_h/boostcamp/myapplication/model/source/local/AppDao.java
  app/src/main/java/team_h/boostcamp/myapplication/view/diaryList/DiaryContract.java
  app/src/main/java/team_h/boostcamp/myapplication/view/diaryList/DiaryListFragment.java
  app/src/main/java/team_h/boostcamp/myapplication/view/diaryList/DiaryPresenter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/diaryList/HashTagListAdapter.java
  app/src/main/res/layout/fragment_diary_list.xml
Labels: Feature, 원종성
