Repository boostcampth/boostcamp3_H, pull requests merged in 2019-02, with the labels that each got.

#74 Feature #073 HashTag Model Create
  app/src/main/java/team_h/boostcamp/myapplication/api/APIClient.java
  app/src/main/java/team_h/boostcamp/myapplication/api/emotion/EmotionAnalysisAPI.java
  app/src/main/java/team_h/boostcamp/myapplication/api/emotion/EmotionAnalysisResponse.java
  app/src/main/java/team_h/boostcamp/myapplication/api/emotion/EmotionAnalyzeRequest.java
  app/src/main/java/team_h/boostcamp/myapplication/api/emotion/mapper/AnalyzedEmotionMapper.java
  app/src/main/java/team_h/boostcamp/myapplication/model/DataRepository.java
  app/src/main/java/team_h/boostcamp/myapplication/model/DataSource.java
  app/src/main/java/team_h/boostcamp/myapplication/model/source/local/DataLocalSource.java
  app/src/main/java/team_h/boostcamp/myapplication/view/diaryList/DiaryPresenter.java
Labels: Feature, 매우간단, 이승우

#76 Fix_#075_피드백 반영
  app/build.gradle
  app/src/main/java/team_h/boostcamp/myapplication/api/deepaffects/DeepAffectApiClient.java
  app/src/main/java/team_h/boostcamp/myapplication/api/deepaffects/EmotionAnalysisAPI.java
  app/src/main/java/team_h/boostcamp/myapplication/api/deepaffects/EmotionAnalysisResponse.java
  app/src/main/java/team_h/boostcamp/myapplication/api/deepaffects/EmotionAnalyzeRequest.java
  app/src/main/java/team_h/boostcamp/myapplication/model/Diary.java
  app/src/main/java/team_h/boostcamp/myapplication/model/source/local/AppDao.java
  app/src/main/java/team_h/boostcamp/myapplication/utils/AnalyzedEmotionMapper.java
  app/src/main/java/team_h/boostcamp/myapplication/view/BaseFragment.java
  app/src/main/java/team_h/boostcamp/myapplication/view/BaseView.java
  app/src/main/java/team_h/boostcamp/myapplication/view/customview/HashTagEditText.java
  app/src/main/java/team_h/boostcamp/myapplication/view/diaryList/DiaryContract.java
  app/src/main/java/team_h/boostcamp/myapplication/view/diaryList/DiaryListFragment.java
  app/src/main/java/team_h/boostcamp/myapplication/view/diaryList/DiaryPresenter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/diarylist/DiaryContract.java
  app/src/main/java/team_h/boostcamp/myapplication/view/diarylist/DiaryListFragment.java
  app/src/main/java/team_h/boostcamp/myapplication/view/diarylist/DiaryPresenter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/diarylist/HashTagListAdapter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/diarylist/MediaRecorderWrapper.java
  app/src/main/java/team_h/boostcamp/myapplication/view/graph/GraphFragment.java
  app/src/main/java/team_h/boostcamp/myapplication/view/main/MainActivity.java
  app/src/main/java/team_h/boostcamp/myapplication/view/memories/MemoriesContractor.java
  app/src/main/java/team_h/boostcamp/myapplication/view/memories/MemoriesFragment.java
  app/src/main/java/team_h/boostcamp/myapplication/view/play/PlayActivity.java
  app/src/main/res/layout/fragment_diary_list.xml
  app/src/main/res/values/strings.xml
  gradle.properties
Labels: Fix, 원종성

#79 Feature #078 주석 제거 및 사용되지 않는 코드 제거
  app/src/main/java/team_h/boostcamp/myapplication/view/graph/GraphAxisValueFormatter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/graph/GraphFragment.java
  app/src/main/java/team_h/boostcamp/myapplication/view/graph/GraphPresenter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/graph/GraphYAxisValueFormatter.java
Labels: Fix, 매우간단, 이승우

#82 Feature #080 multi graph
  app/src/main/java/team_h/boostcamp/myapplication/view/graph/GraphContractor.java
  app/src/main/java/team_h/boostcamp/myapplication/view/graph/GraphFragment.java
  app/src/main/java/team_h/boostcamp/myapplication/view/graph/GraphPresenter.java
  app/src/main/res/values/colors.xml
Labels: Feature, 매우간단, 이승우

#84 Feature #083설정 화면 레이아웃 구성
  app/src/main/AndroidManifest.xml
  app/src/main/java/team_h/boostcamp/myapplication/view/main/MainActivity.java
  app/src/main/java/team_h/boostcamp/myapplication/view/setting/SettingActivity.java
  app/src/main/res/drawable-v24/close_button.png
  app/src/main/res/drawable-v24/next_button.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: Feature, 이승우

#86 Feature #085 화면 전환 및 알람 화면 구성
  app/src/main/AndroidManifest.xml
  app/src/main/java/team_h/boostcamp/myapplication/view/main/MainActivity.java
  app/src/main/java/team_h/boostcamp/myapplication/view/setting/AlarmActivity.java
  app/src/main/java/team_h/boostcamp/myapplication/view/setting/SettingActivity.java
  app/src/main/res/drawable-v24/back_button.png
  app/src/main/res/drawable-v24/settings.png
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/fragment_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Feature, 매우간단, 이승우

#87 Feature/#019 recommend
  app/build.gradle
  app/src/main/java/team_h/boostcamp/myapplication/model/Recommendation.java
  app/src/main/java/team_h/boostcamp/myapplication/model/source/local/AppDao.java
  app/src/main/java/team_h/boostcamp/myapplication/model/source/local/AppDatabase.java
  app/src/main/java/team_h/boostcamp/myapplication/view/memories/MemoriesCardAdapter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/memories/MemoriesDiaryAdapter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/memories/MemoriesFragment.java
  app/src/main/java/team_h/boostcamp/myapplication/view/memories/MemoriesPresenter.java
  app/src/main/res/drawable/back_button.png
  app/src/main/res/drawable/close_button.png
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_main_settings.xml
  app/src/main/res/drawable/next_button.png
  app/src/main/res/drawable/settings.png
  app/src/main/res/values/strings.xml
Labels: Feature, 이화중

#89 Feature/#020 playrecordedfile
  app/src/main/java/team_h/boostcamp/myapplication/model/source/local/AppDao.java
  app/src/main/java/team_h/boostcamp/myapplication/view/play/MediaPlayerWrapper.java
  app/src/main/java/team_h/boostcamp/myapplication/view/play/PlayActivity.java
  app/src/main/java/team_h/boostcamp/myapplication/view/play/PlayContractor.java
  app/src/main/java/team_h/boostcamp/myapplication/view/play/PlayDiaryAdapter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/play/PlayPresenter.java
  app/src/main/res/layout/activity_play.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/item_diary.xml
  app/src/main/res/layout/item_memory_card.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: Feature, 이화중

#90 Feature #026 feat 알람 반복 설정
  app/src/main/java/team_h/boostcamp/myapplication/view/alarm/AlarmActivity.java
  app/src/main/java/team_h/boostcamp/myapplication/view/alarm/AlarmPresenter.java
  app/src/main/res/values/styles.xml
Labels: Feature, 매우간단, 이승우

#91 Feature #027 비밀번호 설정 화면 구성
  app/src/main/AndroidManifest.xml
  app/src/main/java/team_h/boostcamp/myapplication/view/password/PasswordActivity.java
  app/src/main/java/team_h/boostcamp/myapplication/view/password/PasswordContractor.java
  app/src/main/java/team_h/boostcamp/myapplication/view/password/PasswordPresenter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/setting/SettingActivity.java
  app/src/main/res/layout/activity_password.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Feature, 이승우

#95 #093_refactor_playactivity refactoring
  app/src/main/java/team_h/boostcamp/myapplication/view/play/PlayActivity.java
  app/src/main/java/team_h/boostcamp/myapplication/view/play/PlayContractor.java
  app/src/main/java/team_h/boostcamp/myapplication/view/play/PlayPresenter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/play/RecordPlayer.java
  app/src/main/java/team_h/boostcamp/myapplication/view/play/RecordPlayerImpl.java
  app/src/main/res/layout/activity_play.xml
  app/src/main/res/layout/item_memory_card.xml
Labels: Fix, 이화중

#96 Feature #094 modify 알람 화면 리팩토링
  app/src/main/java/team_h/boostcamp/myapplication/view/Handlers.java
  app/src/main/java/team_h/boostcamp/myapplication/view/alarm/AlarmActivity.java
  app/src/main/java/team_h/boostcamp/myapplication/view/alarm/AlarmContractor.java
  app/src/main/java/team_h/boostcamp/myapplication/view/alarm/AlarmPresenter.java
  app/src/main/java/team_h/boostcamp/myapplication/view/alarm/TimePickerFragment.java
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/toolbar_layout.xml
  app/src/main/res/values/strings.xml
Labels: Fix, 매우간단, 이승우

#106 #104 Diary 클래스 재작성
  app/src/main/java/teamh/boostcamp/myapplication/data/local/room/AppDatabase.java
  app/src/main/java/teamh/boostcamp/myapplication/data/local/room/dao/AppDao.java
  app/src/main/java/teamh/boostcamp/myapplication/data/local/room/dao/DiaryDao.java
  app/src/main/java/teamh/boostcamp/myapplication/data/model/Diary.java
  app/src/main/java/teamh/boostcamp/myapplication/data/model/Emotion.java
  app/src/main/java/teamh/boostcamp/myapplication/data/model/LegacyDiary.java
  app/src/main/java/teamh/boostcamp/myapplication/data/model/Recommendation.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/DiaryRepository.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/DiaryRepositoryContract.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/DiaryContract.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/DiaryListAdapter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/DiaryListFragment.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/DiaryPresenter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/memories/MemoriesCardAdapter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/memories/MemoriesDiaryAdapter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/memories/MemoriesPresenter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/play/PlayActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/play/PlayContractor.java
  app/src/main/java/teamh/boostcamp/myapplication/view/play/PlayDiaryAdapter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/play/RecordPlayer.java
  app/src/main/java/teamh/boostcamp/myapplication/view/play/RecordPlayerImpl.java
  app/src/main/res/layout/item_record_diary.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
Labels: Feature

#110 #108 추억 화면 데이터클래스
  app/src/main/java/teamh/boostcamp/myapplication/data/model/Recall.java
Labels: 이화중

#114 #112 RecallRepository interface 생성
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/RecallRepository.java
Labels: 이화중

#113 #111 DiaryRepository Interface 작성
  app/src/main/java/teamh/boostcamp/myapplication/data/model/Diary.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/DiaryRepository.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/LegacyDiaryRepository.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/LegacyDiaryRepositoryContract.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/DiaryListFragment.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/DiaryPresenter.java
Labels: Feature, 원종성

#109 # 107 통계 화면 데이터 클래스 작성
  app/src/main/java/teamh/boostcamp/myapplication/data/local/SharedPreference.java
  app/src/main/java/teamh/boostcamp/myapplication/data/model/CountedTag.java
  app/src/main/java/teamh/boostcamp/myapplication/data/model/EmotionHistory.java
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/AlarmPresenter.java
Labels: 이승우

#118 # 117 그래프, 해시태그 Repository 생성
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/StatisticsRepository.java
Labels: 이승우

#121 # 120 통계 Repository 및 EmotionHistory 클래스 수정
  app/src/main/java/teamh/boostcamp/myapplication/data/model/EmotionHistory.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/StatisticsRepository.java
Labels: 이승우

#124 # 122 statistics repository 구현 및 Dao 작성
  app/src/main/java/teamh/boostcamp/myapplication/data/local/room/AppDatabase.java
  app/src/main/java/teamh/boostcamp/myapplication/data/local/room/dao/DiaryDao.java
  app/src/main/java/teamh/boostcamp/myapplication/data/model/EmotionHistory.java
  app/src/main/java/teamh/boostcamp/myapplication/data/model/EmotionType.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/StatisticsRepository.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/StatisticsRepositoryImpl.java
Labels: 이승우

#123 #115 recall repository 구현 및 DB
  .gitignore
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/java/teamh/boostcamp/myapplication/data/local/room/AppDatabase.java
  app/src/main/java/teamh/boostcamp/myapplication/data/local/room/converter/DateTypeConverter.java
  app/src/main/java/teamh/boostcamp/myapplication/data/local/room/dao/DiaryDao.java
  app/src/main/java/teamh/boostcamp/myapplication/data/local/room/dao/RecallDao.java
  app/src/main/java/teamh/boostcamp/myapplication/data/local/room/entity/RecallEntity.java
  app/src/main/java/teamh/boostcamp/myapplication/data/model/Recall.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/RecallRepository.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/RecallRepositoryImpl.java
Labels: 이화중

#133 # 130 create presenter view interface
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/StatisticsRepositoryImpl.java
  app/src/main/java/teamh/boostcamp/myapplication/view/graph/LegacyGraphFragment.java
  app/src/main/java/teamh/boostcamp/myapplication/view/graph/LegacyGraphPresenter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/graph/StatisticsPresenter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/graph/StatisticsView.java
  app/src/main/java/teamh/boostcamp/myapplication/view/main/MainActivity.java
  app/src/main/res/layout/fragment_graph.xml
Labels: 이승우

#137 #127 recall presenter, view 인터페이스 / view 구현
  app/src/main/java/teamh/boostcamp/myapplication/data/local/room/dao/RecallDao.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/RecallRepositoryImpl.java
  app/src/main/java/teamh/boostcamp/myapplication/view/main/MainActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/memories/LegacyMemoriesPresenter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/memories/MemoriesFragment.java
  app/src/main/java/teamh/boostcamp/myapplication/view/recall/DiaryTitleListAdapter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/recall/RecallFragment.java
  app/src/main/java/teamh/boostcamp/myapplication/view/recall/RecallListAdapter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/recall/RecallPresenter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/recall/RecallView.java
  app/src/main/res/layout/fragment_recall.xml
  app/src/main/res/layout/item_diarytitle_llist.xml
  app/src/main/res/layout/item_recall_list.xml
Labels: Feature, 이화중

#140 # 134 Statistics view 구현
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/StatisticsRepository.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/StatisticsRepositoryImpl.java
  app/src/main/java/teamh/boostcamp/myapplication/view/graph/LegacyGraphPresenter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/graph/StatisticsFragment.java
  app/src/main/java/teamh/boostcamp/myapplication/view/graph/StatisticsPresenter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/graph/StatisticsView.java
  app/src/main/java/teamh/boostcamp/myapplication/view/main/MainActivity.java
Labels: Feature, 이승우

#143 #139-추억생성기능 repository 인터페이스 및 구현, #142-추억 로드 오류수정
  app/src/main/java/teamh/boostcamp/myapplication/data/local/room/AppDatabase.java
  app/src/main/java/teamh/boostcamp/myapplication/data/local/room/dao/RecallDao.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/RecallRepository.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/RecallRepositoryImpl.java
  app/src/main/java/teamh/boostcamp/myapplication/view/recall/DiaryTitleListAdapter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/recall/RecallFragment.java
  app/src/main/java/teamh/boostcamp/myapplication/view/recall/RecallListAdapter.java
Labels: Feature, Fix, 이화중

#148 # issue 145 alram 화면 수정
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 매우간단, 이승우

#151 issue-149- AlarmHelper interface 설계
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/AlarmActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/AlarmContractor.java
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/AlarmHelper.java
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/AlarmHelperImpl.java
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/AlarmPresenter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/AlarmView.java
  app/src/main/res/values/strings.xml
Labels: Fix, 이승우

#154 # issue 153 modify alarm setting
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/AlarmActivity.java
  app/src/main/res/values/strings.xml
Labels: 이승우

#161 # issue-160-fix error resolve
  app/src/main/java/teamh/boostcamp/myapplication/data/local/room/AppDatabase.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/DiaryListFragment.java
  app/src/main/java/teamh/boostcamp/myapplication/view/graph/GraphAxisValueFormatter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/graph/StatisticsFragment.java
Labels: Fix, 이승우

#163 # issue 162 비밀번호 설정 화면 관련 작업
  app/src/main/AndroidManifest.xml
  app/src/main/java/teamh/boostcamp/myapplication/view/password/LockHelper.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/LockHelperImpl.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/LockManager.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordContractor.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordPresenter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordSelectActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordView.java
  app/src/main/java/teamh/boostcamp/myapplication/view/setting/SettingActivity.java
  app/src/main/res/layout/activity_password_select.xml
  app/src/main/res/values/strings.xml
Labels: 이승우

#165 #158 일기 작성 기본 기능 완성
  app/src/main/java/teamh/boostcamp/myapplication/data/local/room/AppDatabase.java
  app/src/main/java/teamh/boostcamp/myapplication/data/local/room/dao/AppDao.java
  app/src/main/java/teamh/boostcamp/myapplication/data/local/room/dao/DiaryDao.java
  app/src/main/java/teamh/boostcamp/myapplication/data/local/room/dao/LegacyDiaryDao.java
  app/src/main/java/teamh/boostcamp/myapplication/data/model/LegacyDiary.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/DataLocalSource.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/DataRepository.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/DataSource.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/DiaryRepository.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/DiaryRepositoryImpl.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/mapper/AnalyzedEmotionMapper.java
  app/src/main/java/teamh/boostcamp/myapplication/utils/HashTagParser.java
  app/src/main/java/teamh/boostcamp/myapplication/utils/ResourceSendUtil.java
  app/src/main/java/teamh/boostcamp/myapplication/view/BaseActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/BaseFragment.java
  app/src/main/java/teamh/boostcamp/myapplication/view/BasePresenter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/BaseView.java
  app/src/main/java/teamh/boostcamp/myapplication/view/adapter/AdapterContract.java
  app/src/main/java/teamh/boostcamp/myapplication/view/adapter/BaseRecyclerViewAdapter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/adapter/OnItemClickListener.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/DiaryListAdapter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/DiaryListFragment.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/DiaryListPresenter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/DiaryListView.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/HashTagListAdapter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/OnHashTagItemClickListener.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/OnRecordItemClickListener.java
  app/src/main/java/teamh/boostcamp/myapplication/view/graph/GraphAxisValueFormatter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/graph/GraphContractor.java
  app/src/main/java/teamh/boostcamp/myapplication/view/graph/LegacyGraphFragment.java
  app/src/main/java/teamh/boostcamp/myapplication/view/graph/LegacyGraphPresenter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/graph/StatisticsFragment.java
  app/src/main/java/teamh/boostcamp/myapplication/view/graph/StatisticsPresenter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/main/MainActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/main/MainActivityView.java
  app/src/main/java/teamh/boostcamp/myapplication/view/main/MainContractor.java
  app/src/main/java/teamh/boostcamp/myapplication/view/main/MainPresenter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordContractor.java
  app/src/main/java/teamh/boostcamp/myapplication/view/play/PlayActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/play/RecordPlayerImpl.java
  app/src/main/java/teamh/boostcamp/myapplication/view/setting/SettingActivity.java
  app/src/main/res/layout/fragment_graph.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/teamh/boostcamp/myapplication/utils/HashTagPaserTest.java
Labels: Feature

#166 # issue 164 password implement
  app/src/main/AndroidManifest.xml
  app/src/main/java/teamh/boostcamp/myapplication/view/Handlers.java
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/AlarmActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/AlarmView.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/LifecycleListener.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/LifecycleManageActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/LockHelper.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/LockHelperImpl.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordSelectActivity.java
  app/src/main/res/anim/anim_shake_cycle.xml
  app/src/main/res/anim/anim_shake_password_not_match.xml
  app/src/main/res/drawable/button_background.xml
  app/src/main/res/drawable/button_normal.xml
  app/src/main/res/drawable/button_pressed.xml
  app/src/main/res/drawable/edittext_background.xml
  app/src/main/res/drawable/edittext_normal.xml
  app/src/main/res/drawable/edittext_pressed.xml
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/activity_password.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 이승우

#171 # issue-169 피드백 반영
  app/src/main/java/teamh/boostcamp/myapplication/data/local/SharedPreferenceManager.java
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/AlarmActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/AlarmHelperImpl.java
  app/src/test/java/teamh/boostcamp/myapplication/util/SharedPreferenceManagerTest.java
Labels: 이승우

#176 # issue 172 fix password
  app/src/main/java/teamh/boostcamp/myapplication/view/AppInitializer.java
  app/src/main/java/teamh/boostcamp/myapplication/view/main/MainActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/LifecycleListener.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/LifecycleManageActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/LockHelper.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/LockHelperImpl.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/LockManager.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordSelectActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/setting/SettingActivity.java
  app/src/main/res/anim/anim_slide_bottom_to_top.xml
  app/src/main/res/values/strings.xml
Labels: 이승우

#180 Feature/issue 179 primary key change
  app/src/main/java/teamh/boostcamp/myapplication/data/local/room/AppDatabase.java
  app/src/main/java/teamh/boostcamp/myapplication/data/local/room/dao/DiaryDao.java
  app/src/main/java/teamh/boostcamp/myapplication/data/local/room/entity/DiaryEntity.java
  app/src/main/java/teamh/boostcamp/myapplication/data/model/Diary.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/DiaryListFragment.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/DiaryListPresenter.java
  app/src/main/res/layout/item_record_diary.xml
Labels: Fix, 매우간단

#187 # issue 183 login presenter view interface create
  app/build.gradle
  app/google-services.json
  app/src/main/java/teamh/boostcamp/myapplication/view/main/MainActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/setting/SettingActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/setting/SettingView.java
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: 이승우

#188 # issue 183 파이어베이스 Crashlytics 제거
  app/build.gradle
  app/src/main/java/teamh/boostcamp/myapplication/data/local/room/AppDatabase.java
Labels: Fix, 이승우

#193 # issue 190 setting ui improve
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/AlarmHelperImpl.java
  app/src/main/java/teamh/boostcamp/myapplication/view/setting/SettingActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/setting/SettingView.java
  app/src/main/res/anim/anim_left_to_right.xml
  app/src/main/res/anim/anim_right_to_left.xml
  app/src/main/res/drawable/ic_setting_right.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/content_setting.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 이승우

#196 # issue 194 비밀번호 UI 개선
  app/src/main/AndroidManifest.xml
  app/src/main/java/teamh/boostcamp/myapplication/view/password/LegacyPasswordSelectActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordSelectActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/setting/SettingActivity.java
  app/src/main/res/anim/anim_left_to_right.xml
  app/src/main/res/anim/anim_right_to_left.xml
  app/src/main/res/drawable/button_normal.xml
  app/src/main/res/drawable/button_pressed.xml
  app/src/main/res/drawable/edittext_normal.xml
  app/src/main/res/drawable/edittext_pressed.xml
  app/src/main/res/layout/activity_legacy_password_select.xml
  app/src/main/res/layout/activity_password.xml
  app/src/main/res/layout/activity_password_select.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/content_setting.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 이승우

#203 # issue 197 setting activity ui improve
  app/src/main/AndroidManifest.xml
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/AlarmActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/AlarmHelperImpl.java
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/AlarmView.java
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/AlertReceiver.java
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/CustomTimePicker.java
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/TimePickerFragment.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordSelectActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/setting/SettingActivity.java
  app/src/main/res/drawable/ic_alarm_more_black.xml
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/activity_password_select.xml
  app/src/main/res/layout/content_setting.xml
  app/src/main/res/layout/dialog_alarm.xml
  app/src/main/res/values/styles.xml
Labels: 이승우

#206 # issue 205 비밀번호 관련 코드 수정
  app/src/main/java/teamh/boostcamp/myapplication/data/local/SharedPreferenceManager.java
  app/src/main/java/teamh/boostcamp/myapplication/view/main/MainActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/LockHelper.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/LockHelperImpl.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/LockManager.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordContractor.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordPresenter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordSelectActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordView.java
  app/src/main/java/teamh/boostcamp/myapplication/view/setting/SettingActivity.java
  app/src/main/res/layout/activity_password_select.xml
  app/src/main/res/layout/content_setting.xml
  app/src/main/res/values/strings.xml
Labels: Fix, 이승우

#209 issue 207 alarm activity modify and mapper create
  app/src/main/AndroidManifest.xml
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/StatisticsRepositoryImpl.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/mapper/CountedTagListMapper.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/mapper/EmotionHistoryMapper.java
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/AlarmActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/AlarmHelperImpl.java
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/AlarmPresenter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/AlarmView.java
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/CustomTimePicker.java
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/TimePickerFragment.java
  app/src/main/java/teamh/boostcamp/myapplication/view/setting/SettingActivity.java
  app/src/main/res/drawable/button_background_alarm.xml
  app/src/main/res/drawable/switch_track_on.xml
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/content_setting.xml
  app/src/main/res/layout/dialog_alarm.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 이승우

#214 # issue 210 스플래시 화면 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/teamh/boostcamp/myapplication/view/AppInitializer.java
  app/src/main/java/teamh/boostcamp/myapplication/view/SplashActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/AlarmActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/graph/StatisticsFragment.java
  app/src/main/java/teamh/boostcamp/myapplication/view/main/MainActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/LockHelper.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordSelectActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/setting/SettingActivity.java
  app/src/main/res/anim/anim_right_from_left.xml
  app/src/main/res/drawable/splash_background.png
  app/src/main/res/drawable/splash_icon.png
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/content_setting.xml
  app/src/main/res/layout/fragment_graph.xml
Labels: 이승우

#218 # issue 217 statistics modify
  app/src/main/AndroidManifest.xml
  app/src/main/java/teamh/boostcamp/myapplication/view/AppInitializer.java
  app/src/main/java/teamh/boostcamp/myapplication/view/SplashActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/AlarmActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/DiaryListPresenter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/graph/StatisticsFragment.java
  app/src/main/java/teamh/boostcamp/myapplication/view/main/MainActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordSelectActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/setting/SettingActivity.java
  app/src/main/res/values/strings.xml
Labels: 이승우

#222 #219 예외처리 추가
  app/build.gradle
  app/src/main/java/teamh/boostcamp/myapplication/data/local/room/AppDatabase.java
  app/src/main/java/teamh/boostcamp/myapplication/data/local/room/entity/DiaryEntity.java
  app/src/main/java/teamh/boostcamp/myapplication/data/model/Event.java
  app/src/main/java/teamh/boostcamp/myapplication/data/model/ShareDiary.java
  app/src/main/java/teamh/boostcamp/myapplication/data/remote/apis/deepaffects/DeepAffectApiClient.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/DiaryRepositoryImpl.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/RecallRepositoryImpl.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/firebase/DownloadTask.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/firebase/FirebaseRepository.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/firebase/FirebaseRepositoryImpl.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/firebase/UploadTask.java
  app/src/main/java/teamh/boostcamp/myapplication/utils/EventBus.java
  app/src/main/java/teamh/boostcamp/myapplication/utils/NetworkStateUtil.java
  app/src/main/java/teamh/boostcamp/myapplication/view/AppInitializer.java
  app/src/main/java/teamh/boostcamp/myapplication/view/alarm/AlarmActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/DiaryListAdapter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/DiaryListFragment.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/DiaryListPresenter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/DiaryListView.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/DiaryRecorder.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/DiaryRecorderImpl.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/DiaryRxEventBus.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/HashTagInputEditText.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/HashTagListAdapter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/popup/analyzeResult/AnalyzedEmotionShowingDialog.java
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/popup/record/RecordingDiaryDialog.java
  app/src/main/java/teamh/boostcamp/myapplication/view/main/MainActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/setting/DeleteDiaryFileWorker.java
  app/src/main/java/teamh/boostcamp/myapplication/view/setting/SettingActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/setting/SettingPresenter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/setting/SettingView.java
  app/src/main/res/drawable/circular_progress_bar.xml
  app/src/main/res/drawable/circular_progress_bar_background.xml
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/dialog_record_diary.xml
  app/src/main/res/layout/fragment_diary_list.xml
  app/src/main/res/layout/item_record_diary.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: Fix, 원종성

#227 # issue 34
  app/src/main/java/teamh/boostcamp/myapplication/view/main/MainActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/LockHelperImpl.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/statistics/GraphAxisValueFormatter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/statistics/HashTagCustomLayout.java
  app/src/main/java/teamh/boostcamp/myapplication/view/statistics/StatisticsFragment.java
  app/src/main/java/teamh/boostcamp/myapplication/view/statistics/StatisticsPresenter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/statistics/StatisticsView.java
  app/src/main/res/drawable/ic_settings_black_24dp.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_graph.xml
  app/src/main/res/layout/layout_graph_hash_tag.xml
Labels: 이승우

#229 # issue graph change
  app/src/main/java/teamh/boostcamp/myapplication/view/main/MainActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/statistics/StatisticsFragment.java
  app/src/main/java/teamh/boostcamp/myapplication/view/statistics/StatisticsPresenter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/statistics/StatisticsView.java
  app/src/main/res/drawable/analyzed_color_drawable.xml
  app/src/main/res/drawable/selected_color_drawable.xml
  app/src/main/res/layout/fragment_graph.xml
  app/src/main/res/layout/fragment_statistics.xml
Labels: 이승우

#239 # issue 230 error modify memory leak resolve
  app/src/main/java/teamh/boostcamp/myapplication/view/AppInitializer.java
  app/src/main/java/teamh/boostcamp/myapplication/view/main/MainActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/statistics/GraphAxisValueFormatter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/statistics/HashTagCustomLayout.java
  app/src/main/java/teamh/boostcamp/myapplication/view/statistics/StatisticsFragment.java
  app/src/main/java/teamh/boostcamp/myapplication/view/statistics/StatisticsPresenter.java
  app/src/main/res/layout/activity_setting.xml
  app/src/main/res/layout/fragment_statistics.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 이승우

#243 #242 초기화 기능 에러 수정
  app/src/main/java/teamh/boostcamp/myapplication/view/diarylist/DiaryListPresenter.java
Labels: 매우간단, 원종성

#249 # issue 247 fix error
  app/src/main/java/teamh/boostcamp/myapplication/data/local/room/AppDatabase.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/backup/BackUpRepository.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/backup/BackUpRepositoryImpl.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/backup/DownloadTask.java
  app/src/main/java/teamh/boostcamp/myapplication/data/repository/backup/UploadTask.java
  app/src/main/java/teamh/boostcamp/myapplication/view/AppInitializer.java
  app/src/main/java/teamh/boostcamp/myapplication/view/SplashActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/main/MainActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/LockHelper.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/LockHelperImpl.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/LockManager.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordPresenter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordSelectActivity.java
  app/src/main/java/teamh/boostcamp/myapplication/view/password/PasswordView.java
  app/src/main/java/teamh/boostcamp/myapplication/view/setting/SettingPresenter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/statistics/GraphAxisValueFormatter.java
  app/src/main/java/teamh/boostcamp/myapplication/view/statistics/StatisticsFragment.java
  app/src/main/java/teamh/boostcamp/myapplication/view/statistics/StatisticsPresenter.java
  app/src/main/res/layout/activity_password.xml
  app/src/main/res/values/strings.xml
Labels: 이승우
